emails_alunos_1MC = {
    'rafaela.aquino@escola.pr.gov.br': 'RAFAELA ZORDAN AQUINO',
    'luiz.szlachta.oliveira@escola.pr.gov.br': 'LUIZ EDUARDO SZLACHTA DE OLIVEIRA',
    'isadora.gibin.mendes@escola.pr.gov.br': 'ISADORA GIBIN MENDES',
    'heloisa.rigoti.almeida@escola.pr.gov.br': 'HELOISA RIGOTI ALMEIDA',
    'gabrielly.hilario@escola.pr.gov.br': 'GABRIELLY NEGRELI HILARIO',
    'joao.coral@escola.pr.gov.br': 'JOAO PEDRO RODRIGUES CORAL',
    'jose.lajarin.pereira@escola.pr.gov.br': 'JOSE HENRIQUE LAJARIN PEREIRA',
    'emanuel.fernandes.garcia@escola.pr.gov.br': 'EMANUEL FERNANDES GARCIA',
    'levy.nakanishi@escola.pr.gov.br': 'LEVY NAKANISHI',
    'sebasthian.deliborio@escola.pr.gov.br': 'SEBASTHIAN BERTONCINI CORREIA CORDEON DELIBORIO',
    'gabriel.ribeiro.joao2105@escola.pr.gov.br': 'JOAO GABRIEL RIBEIRO',
    'g.boim@escola.pr.gov.br': 'GUILHERME CATORE D AVILA BOIM',
    'nicolle.molina@escola.pr.gov.br': 'NICOLLE AMANCIO MOLINA',
    'beatriz.teixeira.dourado@escola.pr.gov.br': 'BEATRIZ TEIXEIRA DOURADO',
    'lara.rodrigues.oliveira@escola.pr.gov.br': 'LARA SILVA RODRIGUES DE OLIVEIRA',
    'rebeca.buss@escola.pr.gov.br': 'REBECA FERREIRA BUSS',
    'santos.antonio.jose@escola.pr.gov.br': 'JOSE DOS SANTOS ANTONIO',
    'yan.benicio@escola.pr.gov.br': 'YAN EDUARDO TAKENAGA BENICIO',
    'bruno.santos.tobias@escola.pr.gov.br': 'BRUNO SANTOS TOBIAS',
    'silva.santos.maria2107@escola.pr.gov.br': 'MARIA EDUARDA SILVA DOS SANTOS',
    'joao.buono.ferraz@escola.pr.gov.br': 'JOAO PEDRO BUONO FERRAZ',
    'matheus.nogueira.santos03@escola.pr.gov.br': 'MATHEUS NOGUEIRA SANTOS',
    'jamille.bloedorn@escola.pr.gov.br': 'JAMILLE CAROLINE BLOWEDORN',
    'nicolas.andrade.santos04@escola.pr.gov.br': 'NICOLAS ANDRADE DOS SANTOS',
    'davi.souza.vieira@escola.pr.gov.br': 'DAVI FELIPE DE SOUZA VIEIRA',
    'nathan.fleuringer@escola.pr.gov.br': 'NATHAN STREPPEL FLEURINGER',
    'daniel.takahashi@escola.pr.gov.br': 'DANIEL KENICHI TAKAHASHI',
    'paulo.takeda@escola.pr.gov.br': 'PAULO HENRIQUE NOZI TAKEDA',
    'ornellas.ana@escola.pr.gov.br': 'ANA VITORIA VIEIRA DE ORNELLAS',
    'gomes.vinicius@escola.pr.gov.br': 'VINICIUS ARAUJO GOMES',
    'mirella.ferro@escola.pr.gov.br': 'MIRELLA FERRO',
    'lucas.rodrigues.fontana@escola.pr.gov.br': 'LUCAS AUGUSTO RODRIGUES FONTANA',
    'rodrigues.catarina@escola.pr.gov.br': 'CATARINA TONASSE RODRIGUES',
    'pereira.isis@escola.pr.gov.br': 'ISIS LUZ PEREIRA',
    'andre.rodolpho@escola.pr.gov.br': 'ANDRE FURLAN RODOLPHO',
    'enzo.carnelos@escola.pr.gov.br': 'ENZO SOLER CARNELOS',
    'bruno.santi@escola.pr.gov.br': 'BRUNO DE ANDRADE SANTI',
    'mirella.dourado@escola.pr.gov.br': 'MIRELLA TEIXEIRA DOURADO',
    'bryan.massarim.martins@escola.pr.gov.br': 'BRYAN MASSARIM MARTINS',
    'agatha.santos.costa@escola.pr.gov.br': 'AGATHA SANTOS COSTA',
    'monte.sophia@escola.pr.gov.br': 'SOPHIA LARIANE PARENTE SOUZA DO MONTE',
    'f.diego@escola.pr.gov.br': 'DIEGO DE DIO FERREIRA',
    'dio.diego1@gmail.com': 'diego de dio ferreira'
}
