# emails_alunos_1MC = {
#     'rafaela.aquino@escola.pr.gov.br': 'RAFAELA ZORDAN AQUINO',
#     'luiz.szlachta.oliveira@escola.pr.gov.br': 'LUIZ EDUARDO SZLACHTA DE OLIVEIRA',
#     'isadora.gibin.mendes@escola.pr.gov.br': 'ISADORA GIBIN MENDES',
#     'heloisa.rigoti.almeida@escola.pr.gov.br': 'HELOISA RIGOTI ALMEIDA',
#     'gabrielly.hilario@escola.pr.gov.br': 'GABRIELLY NEGRELI HILARIO',
#     'joao.coral@escola.pr.gov.br': 'JOAO PEDRO RODRIGUES CORAL',
#     'jose.lajarin.pereira@escola.pr.gov.br': 'JOSE HENRIQUE LAJARIN PEREIRA',
#     'emanuel.fernandes.garcia@escola.pr.gov.br': 'EMANUEL FERNANDES GARCIA',
#     'levy.nakanishi@escola.pr.gov.br': 'LEVY NAKANISHI',
#     'sebasthian.deliborio@escola.pr.gov.br': 'SEBASTHIAN BERTONCINI CORREIA CORDEON DELIBORIO',
#     'gabriel.ribeiro.joao2105@escola.pr.gov.br': 'JOAO GABRIEL RIBEIRO',
#     'g.boim@escola.pr.gov.br': 'GUILHERME CATORE D AVILA BOIM',
#     'nicolle.molina@escola.pr.gov.br': 'NICOLLE AMANCIO MOLINA',
#     'beatriz.teixeira.dourado@escola.pr.gov.br': 'BEATRIZ TEIXEIRA DOURADO',
#     'lara.rodrigues.oliveira@escola.pr.gov.br': 'LARA SILVA RODRIGUES DE OLIVEIRA',
#     'rebeca.buss@escola.pr.gov.br': 'REBECA FERREIRA BUSS',
#     'santos.antonio.jose@escola.pr.gov.br': 'JOSE DOS SANTOS ANTONIO',
#     'yan.benicio@escola.pr.gov.br': 'YAN EDUARDO TAKENAGA BENICIO',
#     'bruno.santos.tobias@escola.pr.gov.br': 'BRUNO SANTOS TOBIAS',
#     'silva.santos.maria2107@escola.pr.gov.br': 'MARIA EDUARDA SILVA DOS SANTOS',
#     'joao.buono.ferraz@escola.pr.gov.br': 'JOAO PEDRO BUONO FERRAZ',
#     'matheus.nogueira.santos03@escola.pr.gov.br': 'MATHEUS NOGUEIRA SANTOS',
#     'jamille.bloedorn@escola.pr.gov.br': 'JAMILLE CAROLINE BLOWEDORN',
#     'nicolas.andrade.santos04@escola.pr.gov.br': 'NICOLAS ANDRADE DOS SANTOS',
#     'davi.souza.vieira@escola.pr.gov.br': 'DAVI FELIPE DE SOUZA VIEIRA',
#     'nathan.fleuringer@escola.pr.gov.br': 'NATHAN STREPPEL FLEURINGER',
#     'daniel.takahashi@escola.pr.gov.br': 'DANIEL KENICHI TAKAHASHI',
#     'paulo.takeda@escola.pr.gov.br': 'PAULO HENRIQUE NOZI TAKEDA',
#     'ornellas.ana@escola.pr.gov.br': 'ANA VITORIA VIEIRA DE ORNELLAS',
#     'gomes.vinicius@escola.pr.gov.br': 'VINICIUS ARAUJO GOMES',
#     'mirella.ferro@escola.pr.gov.br': 'MIRELLA FERRO',
#     'lucas.rodrigues.fontana@escola.pr.gov.br': 'LUCAS AUGUSTO RODRIGUES FONTANA',
#     'rodrigues.catarina@escola.pr.gov.br': 'CATARINA TONASSE RODRIGUES',
#     'pereira.isis@escola.pr.gov.br': 'ISIS LUZ PEREIRA',
#     'andre.rodolpho@escola.pr.gov.br': 'ANDRE FURLAN RODOLPHO',
#     'enzo.carnelos@escola.pr.gov.br': 'ENZO SOLER CARNELOS',
#     'bruno.santi@escola.pr.gov.br': 'BRUNO DE ANDRADE SANTI',
#     'mirella.dourado@escola.pr.gov.br': 'MIRELLA TEIXEIRA DOURADO',
#     'bryan.massarim.martins@escola.pr.gov.br': 'BRYAN MASSARIM MARTINS',
#     'agatha.santos.costa@escola.pr.gov.br': 'AGATHA SANTOS COSTA',
#     'monte.sophia@escola.pr.gov.br': 'SOPHIA LARIANE PARENTE SOUZA DO MONTE',
#     'f.diego@escola.pr.gov.br': 'DIEGO DE DIO FERREIRA',
#     'dio.diego1@gmail.com': 'diego de dio ferreira',
#     'emanuel.barroso@escola.pr.gov.br': 'EMANUEL DA SILVA JUSTUS BARROSO'
# }

# emails_alunos_1MA = {
#     "a.formighieri@escola.pr.gov.br": "ANA CLARA FORMIGHIERI",
#     "ana.cyrillo.almeida@escola.pr.gov.br": "ANA LUIZA CYRILLO DE ALMEIDA",
#     "arthur.lopes.martins@escola.pr.gov.br": "ARTHUR FELIPE LOPES MARTINS",
#     "bruno.henrique.mendes@escola.pr.gov.br": "BRUNO HENRIQUE MENDES",
#     "davi.donato@escola.pr.gov.br": "DAVI ANTONY CASAROTI DONATO",
#     "davi.boas.gomes@escola.pr.gov.br": "DAVI ZAGO VILAS BOAS GOMES",
#     "eduardo.klem.souza@escola.pr.gov.br": "EDUARDO KLEM DE SOUZA",
#     "felipe.nathan.santos@escola.pr.gov.br": "FELIPE NATHAN DOS SANTOS",
#     "g.vilar@escola.pr.gov.br": "GABRIEL CALEFFI DE JESUS TEIXEIRA VILAR",
#     "gabriel.rodrigues.angelo@escola.pr.gov.br": "GABRIEL RODRIGUES ANGELO",
#     "giovana.fukagawa.souza@escola.pr.gov.br": "GIOVANA FUKAGAWA DE SOUZA",
#     "heloysa.santana.silva@escola.pr.gov.br": "HELOYSA DE SANTANA SILVA",
#     "isabela.guedes.rodrigues@escola.pr.gov.br": "ISABELA MENDONÇA GUEDES RODRIGUES",
#     "isabella.munhoz@escola.pr.gov.br": "ISABELLA NOVAIS MUNHOZ",
#     "isabelli.gomes.oliveira@escola.pr.gov.br": "ISABELLI GOMES DE OLIVEIRA",
#     "izabelly.martins.souza@escola.pr.gov.br": "IZABELLY CAROLINE MARTINS DE SOUZA",
#     "pedro.rossi.joao@escola.pr.gov.br": "JOÃO PEDRO ROSSI",
#     "julia.dimiras@escola.pr.gov.br": "JULIA FIGUEIRA SILVA DIMIRAS",
#     "kyarha.silva@escola.pr.gov.br": "KYARHA OLIVEIRA DA SILVA",
#     "livia.souza.pires@escola.pr.gov.br": "LIVIA DE SOUZA PIRES",
#     "rafaella.pedrosa.araujo@escola.pr.gov.br": "LÍVIA PEDROSA ARAÚJO",
#     "l.russo@escola.pr.gov.br": "LUIZ FERNANDO RUSSO",
#     "luiza.pedroso.melo@escola.pr.gov.br": "LUIZA GUIMARÃES PEDROSO DE MELO",
#     "manuela.caldeira.silva@escola.pr.gov.br": "MANUELA CALDEIRA SILVA",
#     "manuella.dalto@escola.pr.gov.br": "MANUELLA GIROLDO DALTO",
#     "marcela.molina@escola.pr.gov.br": "MARCELA MOLINA",
#     "natalia.pilla@escola.pr.gov.br": "NATÁLIA DOS SANTOS PILLA",
#     "balduino.nathan@escola.pr.gov.br": "NATHAN GUSTAVO DA SILVA BALDUINO",
#     "pedro.miranda.medeiros@escola.pr.gov.br": "PEDRO GABRIEL MIRANDA MEDEIROS",
#     "rafael.santiago.trindade@escola.pr.gov.br": "RAFAEL AUGUSTO SANTIAGO DA TRINDADE",
#     "rafaela.cristina.costa@escola.pr.gov.br": "RAFAELA CRISTINA COSTA",
#     "pedrosa.araujo@escola.pr.gov.br": "RAFAELLA PEDROSA ARAUJO",
#     "stevan.souza@escola.pr.gov.br": "STEVAN JOSÉ COSTA DE SOUZA",
#     "vitor.ribeiro.quadros@escola.pr.gov.br": "VITOR BIDJEY RIBEIRO DE QUADROS",
#     "gabrielly.hilario@escola.pr.gov.br": "GABRIELLY NEGRELI HILARIO",
#     "heloisa.santos.alves@escola.pr.gov.br": "HELOISA VITHORIA DOS SANTOS ALVES",
#     "flavia.souza.franca@escola.pr.gov.br": "FLAVIA SOUZA FRANCA",
#     "davi.torres.moura@escola.pr.gov.br": "DAVI TORRES DE MOURA",
#     'f.diego@escola.pr.gov.br': 'DIEGO DE DIO FERREIRA',
#     'dio.diego1@gmail.com': 'diego de dio ferreira',
# }

# emails_alunos_1MC = {
#     'zacarias.sabrina@escola.pr.gov.br': 'SABRINA VITÓRIA RIBEIRO ZACARIAS',
#     'debora.buss@escola.pr.gov.br': 'DÉBORA FERREIRA BUSS',
#     'y.hipolito@escola.pr.gov.br': 'YASMIN LIMA HIPÓLITO',
#     'theodora.sakai@escola.pr.gov.br': 'THEODORA VIDOTI SAKAI',
#     'sergio.muller.borges@escola.pr.gov.br': 'SERGIO EMMANUEL MULLER BORGES',
#     'mendes.ana21@escola.pr.gov.br': 'ANA LUIZA DE OLIVEIRA MENDES',
#     'ferrari.gabrielly@escola.pr.gov.br': 'GABRIELLY MEDEIROS FERRARI',
#     'thiago.silva.miranda@escola.pr.gov.br': 'THIAGO SILVA MIRANDA',
#     'briyan.sato@escola.pr.gov.br': 'BRIYAN YUDI SATO',
#     'theo.goncalves.silva@escola.pr.gov.br': 'THÉO RODRIGUES GONÇALVES DA SILVA',
#     'ramir.maluf@escola.pr.gov.br': 'RAMIR YOSSEF VICTOR MALUF',
#     'camargo.souza.gabriel@escola.pr.gov.br': 'GABRIEL BETRAN CAMARGO DE SOUZA',
#     'matheus.rodrigues.santos20@escola.pr.gov.br': 'MATHEUS FABRICIO RODRIGUES DOS SANTOS',
#     'maria.caetano.barboza@escola.pr.gov.br': 'MARIA EDUARDA CAETANO BARBOZA',
#     'crastechini.guilherme@escola.pr.gov.br': 'GUILHERME ENZO HAYASHI CRASTECHINI',
#     'conezza.jhonata@escola.pr.gov.br': 'JHONATA GABRIEL CORRÊA CONEZZA',
#     'paloma.silva09@escola.pr.gov.br': 'PALOMA RODRIGUES DA SILVA',
#     'guilherme.borges.silva20@escola.pr.gov.br': 'GUILHERME MORI BORGES DA SILVA',
#     'emanuel.marigo@escola.pr.gov.br': 'EMANUEL ALVES MARIGO',
#     'beatriz.amanda.silva@escola.pr.gov.br': 'BEATRIZ AMANDA DA SILVA',
#     #'daniel.agostini@escola.pr.gov.br': 'DANIEL AGOSTINI',
#     'miley.torrez@escola.pr.gov.br': 'MILEY BEZERRA TORREZ',
#     'ornellas.luiz@escola.pr.gov.br': 'LUIZ FELIPE DE SOUZA ORNELLAS',
#     'davi.bacelar.pacheco@escola.pr.gov.br': 'DAVI BACELAR PACHECO',
#     'luiz.stanganelli.furtado@escola.pr.gov.br': 'LUIZ MIGUEL MESSA RODRIGUES',
#     'pedro.mendes.leal@escola.pr.gov.br': 'PEDRO HENRIQUE MENDES LEAL',
#     'rafaela.agostini.rodrigues@escola.pr.gov.br': 'RAFAELA AGOSTINI RODRIGUES',
#     'clara.harmuch.melo@escola.pr.gov.br': 'CLARA HARMUCH MELO',
#     'laura.alvin.silva@escola.pr.gov.br': 'LAURA ALVIN DA SILVA',
#     'julya.tsujiguchi@escola.pr.gov.br': 'JULYA FERREIRA TSUJIGUCHI',
#     'giovanna.busto@escola.pr.gov.br': 'GIOVANNA STHEPHANY VITOR BUSTO',
#     'lima.martins.samuel@escola.pr.gov.br': 'SAMUEL LIMA MARTINS',
#     'andressa.lopes.siqueira@escola.pr.gov.br': 'ANDRESSA LOPES DE SIQUEIRA',
#     'joao.castro.maximo@escola.pr.gov.br': 'JOÃO HENRIQUE DE CASTRO MAXIMO',
#     'asso.paolla@escola.pr.gov.br': 'PAOLLA CAROBELLI ASSO',
#     'regina.galvao@escola.pr.gov.br': 'BIANCA REGINA GALVÃO',
#     'luiz.messa.rodrigues@escola.pr.gov.br': 'LUIZ MIGUEL MESSA RODRIGUES',
#     'felipe.cano@escola.pr.gov.br': 'FELIPE DELFINO CANO',
#     'maria.seregni.souza@escola.pr.gov.br': 'MARIA ELOISA SEREGNI DE SOUZA',
#     'william.corte@escola.pr.gov.br': 'WILLIAM FERREIRA CORTE',
#     'ester.monteiro@escola.pr.gov.br': 'ESTER CAMPOLI MONTEIRO',
#     'f.diego@escola.pr.gov.br': 'DIEGO DE DIO FERREIRA',
#     'dio.diego1@gmail.com': 'diego de dio ferreira',
# }

emails_alunos_1MC = {
    'zacarias.sabrina@escola.pr.gov.br': 'SABRINA VITÓRIA RIBEIRO ZACARIAS',
    'debora.buss@escola.pr.gov.br': 'DÉBORA FERREIRA BUSS',
    'y.hipolito@escola.pr.gov.br': 'YASMIN LIMA HIPÓLITO',
    'theodora.sakai@escola.pr.gov.br': 'THEODORA VIDOTI SAKAI',
    'sergio.muller.borges@escola.pr.gov.br': 'SERGIO EMMANUEL MULLER BORGES',
    'mendes.ana21@escola.pr.gov.br': 'ANA LUIZA DE OLIVEIRA MENDES',
    'ferrari.gabrielly@escola.pr.gov.br': 'GABRIELLY MEDEIROS FERRARI',
    'thiago.silva.miranda@escola.pr.gov.br': 'THIAGO SILVA MIRANDA',
    'briyan.sato@escola.pr.gov.br': 'BRIYAN YUDI SATO',
    'theo.goncalves.silva@escola.pr.gov.br': 'THÉO RODRIGUES GONÇALVES DA SILVA',
    'ramir.maluf@escola.pr.gov.br': 'RAMIR YOSSEF VICTOR MALUF',
    'camargo.souza.gabriel@escola.pr.gov.br': 'GABRIEL BETRAN CAMARGO DE SOUZA',
    'matheus.rodrigues.santos20@escola.pr.gov.br': 'MATHEUS FABRICIO RODRIGUES DOS SANTOS',
    'maria.caetano.barboza@escola.pr.gov.br': 'MARIA EDUARDA CAETANO BARBOZA',
    'crastechini.guilherme@escola.pr.gov.br': 'GUILHERME ENZO HAYASHI CRASTECHINI',
    'conezza.jhonata@escola.pr.gov.br': 'JHONATA GABRIEL CORRÊA CONEZZA',
    'paloma.silva09@escola.pr.gov.br': 'PALOMA RODRIGUES DA SILVA',
    'guilherme.borges.silva20@escola.pr.gov.br': 'GUILHERME MORI BORGES DA SILVA',
    'emanuel.marigo@escola.pr.gov.br': 'EMANUEL ALVES MARIGO',
    'beatriz.amanda.silva@escola.pr.gov.br': 'BEATRIZ AMANDA DA SILVA',
    'daniel.agostini@escola.pr.gov.br': 'DANIEL AGOSTINI',
    'miley.torrez@escola.pr.gov.br': 'MILEY BEZERRA TORREZ',
    'ornellas.luiz@escola.pr.gov.br': 'LUIZ FELIPE DE SOUZA ORNELLAS',
    'davi.bacelar.pacheco@escola.pr.gov.br': 'DAVI BACELAR PACHECO',
    'luiz.stanganelli.furtado@escola.pr.gov.br': 'LUIZ MIGUEL MESSA RODRIGUES',
    'pedro.mendes.leal@escola.pr.gov.br': 'PEDRO HENRIQUE MENDES LEAL',
    'rafaela.agostini.rodrigues@escola.pr.gov.br': 'RAFAELA AGOSTINI RODRIGUES',
    'clara.harmuch.melo@escola.pr.gov.br': 'CLARA HARMUCH MELO',
    'laura.alvin.silva@escola.pr.gov.br': 'LAURA ALVIN DA SILVA',
    'julya.tsujiguchi@escola.pr.gov.br': 'JULYA FERREIRA TSUJIGUCHI',
    'giovanna.busto@escola.pr.gov.br': 'GIOVANNA STHEPHANY VITOR BUSTO',
    'lima.martins.samuel@escola.pr.gov.br': 'SAMUEL LIMA MARTINS',
    'andressa.lopes.siqueira@escola.pr.gov.br': 'ANDRESSA LOPES DE SIQUEIRA',
    'joao.castro.maximo@escola.pr.gov.br': 'JOÃO HENRIQUE DE CASTRO MAXIMO',
    'asso.paolla@escola.pr.gov.br': 'PAOLLA CAROBELLI ASSO',
    'regina.galvao@escola.pr.gov.br': 'BIANCA REGINA GALVÃO',
    'luiz.messa.rodrigues@escola.pr.gov.br': 'LUIZ MIGUEL MESSA RODRIGUES',
    'felipe.cano@escola.pr.gov.br': 'FELIPE DELFINO CANO',
    'maria.seregni.souza@escola.pr.gov.br': 'MARIA ELOISA SEREGNI DE SOUZA',
    'william.corte@escola.pr.gov.br': 'WILLIAM FERREIRA CORTE',
    'ester.monteiro@escola.pr.gov.br': 'ESTER CAMPOLI MONTEIRO',
    'izadora.rodrigues.cruz@escola.pr.gov.br': 'IZADORA RODRIGUES CRUZ',
    'anna.almeida.pessoa@escola.pr.gov.br': 'ANNA CLARA ALMEIDA PESSOA',
    'silva.coelho.davi@escola.pr.gov.br': 'DAVI SILVA COELHO',
    'estephani.antunes@escola.pr.gov.br': 'ESTEPHANI NICOLLY COTES ANTUNES',
    'lorrayne.santos.fonseca@escola.pr.gov.br': 'LORRAYNE NATIELE DAMASIO SANTOS FONSECA',
    'g.moreto@escola.pr.gov.br': 'GUSTAVO MACHADO MORETO',
    'maria.eduarda.lopes29@escola.pr.gov.br': 'MARIA EDUARDA LOPES',
    'campina.pietro@escola.pr.gov.br': 'PIETRO EDUARDO ALVES CAMPINA',
    'isabela.slobogian@escola.pr.gov.br': 'ISABELA RIBEIRO SLOBOGIAN',
    'emilly.vidal17@escola.pr.gov.br': 'EMILLY VIDAL',
    'leonardo.francisco.camargo@escola.pr.gov.br': 'LEONARDO FRANCISCO CAMARGO',
    'kemelly.vieira.silva@escola.pr.gov.br': 'KEMELLY VIEIRA DA SILVA',
    'juliana.heller@escola.pr.gov.br': 'JULIANA BEATRIZ SILVA HELLER',
    'ignacio.kaua@escola.pr.gov.br': 'KAUÃ IGNACIO',  
    'beatriz.alarcon.melo@escola.pr.gov.br': 'BEATRIZ ALARCÓN MELO',
    'maria.oliveira.menezes@escola.pr.gov.br': 'MARIA JULIA DE OLIVEIRA DE MENEZES',
    'bueno.lourenco.isadora@escola.pr.gov.br': 'ISADORA DE CAMARGO BUENO LOURENÇO',
    'danilo.balman@escola.pr.gov.br': 'DANILO BALMAN',
    'sobral.pedro@escola.pr.gov.br': 'PEDRO HENRIQUE SOBRAL',
    'thaina.honorato@escola.pr.gov.br': 'THAINA MIKAELE GOMES HONORATO',
    'brizola.debora@escola.pr.gov.br': 'DÉBORA VITORIA SOARES BRIZOLA',
    'maria.diniz.silva05@escola.pr.gov.br': 'MARIA LUIZA DINIZ DA SILVA',
    'evellyn.viana.santos@escola.pr.gov.br': 'EVELLYN BEATRIZ VIANA DOS SANTOS',
    'nathan.elias.souza@escola.pr.gov.br': 'NATHAN ELIAS DE SOUZA',
    'beatriz.moraes.machado@escola.pr.gov.br': 'BEATRIZ MARQUES DE MORAES MACHADO',
    'carvalho.santos.gabrielly@escola.pr.gov.br': 'GABRIELLY VITORIA CARVALHO SANTOS',
    'lais.santos.rocha@escola.pr.gov.br': 'LAÍS SANTOS DA ROCHA',
    'lara.resende.santos@escola.pr.gov.br': 'LARA RESENDE SANTOS',
    'maria.bezerra21@escola.pr.gov.br': 'MARIA BEZERRA',
    'ezequiel.rojas@escola.pr.gov.br': 'EZEQUIEL ANTONIO FLORES ROJAS',
    'jose.marondes@escola.pr.gov.br': 'JOSÉ AUGUSTO ASSUNÇÃO MARONDES',
    'eloa.santos.marques@escola.pr.gov.br': 'ELOÁ SANTOS MARQUES',
    's.anna03@escola.pr.gov.br': 'ANNA VITORIA DE SOUZA DA SILVA',
    'natalia.gonzaga@escola.pr.gov.br': 'NATÁLIA BEATRIZ GONZAGA',
    'gabriel.pinto.velozo@escola.pr.gov.br': 'GABRIEL PINTO VELOZO',
    'jheniffer.simoes.alves@escola.pr.gov.br': 'JHENIFFER LOHAINE SIMÕES ALVES',
    'isabelly.augusto.silva@escola.pr.gov.br': 'ISABELLY AUGUSTO DA SILVA',
    'ana.joventino@escola.pr.gov.br': 'ANA CLARA FRANCO JOVENTINO',
    'ana.vedovato@escola.pr.gov.br': 'ANA LUIZA VEDOVATO',
    'alberto.morais.neto@escola.pr.gov.br': 'ALBERTO MORAIS NETO',
    'emilly.viana.santos@escola.pr.gov.br': 'EMILLY FERNANDA VIANA DOS SANTOS',
    'emanuelly.maximo@escola.pr.gov.br': 'EMANUELLY CRISTINA MAXIMO',
    'bianca.macri@escola.pr.gov.br': 'BIANCA MACRI',
    'antonio.macedo.netto@escola.pr.gov.br': 'ANTONIO RODRIGUES DE MACEDO NETTO',
    'santos.pereira.ana2209@escola.pr.gov.br': 'ANA JULIA DOS SANTOS PEREIRA',
    'thuanny.fermino@escola.pr.gov.br': 'THUANNY SANCHES FERMINO',
    'f.diego@escola.pr.gov.br': 'DIEGO DE DIO FERREIRA',
    'dio.diego1@gmail.com': 'diego de dio ferreira',
    ####1mkt
    'juan.vieira.barros@escola.pr.gov.br': 'JUAN PABLO VIEIRA BARROS',
    'leticia.santos.silva25@escola.pr.gov.br': 'LETICIA GABRIELLA SANTOS DA SILVA',
    'lorainy.donaire@escola.pr.gov.br': 'LORAINY BEATRIZ DA SILVA DONAIRE',
    'nicolly.agatha.nascimento@escola.pr.gov.br': 'NICOLLY AGATHA DO NASCIMENTO',
    'neves.victoria@escola.pr.gov.br': 'VICTÓRIA EMANUELLY FERREIRA DAS NEVES',
    'marijulene.goncalves@escola.pr.gov.br': 'MARIJULENE SILVA GONÇALVES',
    'julio.fonseca.borges@escola.pr.gov.br': 'JULIO CESAR FONSECA BORGES',
    'lima.silva.emanuelle@escola.pr.gov.br': 'EMANUELLE ROSA LIMA DA SILVA',
    'regina.oliveira.layra@escola.pr.gov.br': 'LAYRA REGINA DE OLIVEIRA',
    'paes.nathan@escola.pr.gov.br': 'NATHAN RODRIGUES PAES',
    'livia.moco.moreira@escola.pr.gov.br': 'LIVIA TAVARES MOÇO MOREIRA',
    'henrique.geraldo.araujo@escola.pr.gov.br': 'HENRIQUE GERALDO DE ARAUJO',
    'joao.marques.adriano@escola.pr.gov.br': 'JOÃO LUCAS MARQUES ADRIANO',
    'h.angelo@escola.pr.gov.br': 'HELOÍSA PEREIRA DO ANGELO',
    'icaro.emanuel.silva@escola.pr.gov.br': 'ÍCARO EMANOEL DA SILVA',
    'matheus.melo.guilherme@escola.pr.gov.br': 'MATHEUS BEZERRO DE MELO GUILHERME',
    'nicoly.santos26@escola.pr.gov.br': 'NICOLY GABRIELLI OLIVEIRA DOS SANTOS',
    'paola.larissa.bueno@escola.pr.gov.br': 'PAOLA LARISSA BUENO',
    'sara.cantuario@escola.pr.gov.br': 'SARA SABRYNE ARAUJO CANTUARIO',
    'ana.kremer@escola.pr.gov.br': 'ANA LUIZA BAPTISTA KREMER',
    'karolaine.oliveira.borges@escola.pr.gov.br': 'KAROLAINE GONÇALVES DE OLIVEIRA BORGES',
    'maria.melo.germano@escola.pr.gov.br': 'MARIA JULIA DE ANDRADE MELO GERMANO',
    'bianca.rodrigues.oliveira31@escola.pr.gov.br': 'BIANCA RODRIGUES DE OLIVEIRA',
    'maria.monteiro.oliveira05@escola.pr.gov.br': 'MARIA EDUARDA LIMA SILVA',
    'maria.eduarda.lopes29@escola.pr.gov.br': 'MARIA EDUARDA LOPES',
    'lima.silva.maria2307@escola.pr.gov.br': 'MARIA EDUARDA LIMA SILVA',
    'pedro.pereira.souza18@escola.pr.gov.br': 'PEDRO HENRIQUE PEREIRA DE SOUZA',
    'davi.silva.melo@escola.pr.gov.br': 'DAVI GABRIEL RODRIGUES DA SILVA MELO',
    'lucas.puerta.guimaraes@escola.pr.gov.br': 'LUCAS PUERTA GUIMARÃES',
    'lucas.gabriel.silva08@escola.pr.gov.br': 'LUCAS GABRIEL DA SILVA',
    'felipe.luiz.freire@escola.pr.gov.br': 'FELIPE VIOL LUIZ FREIRE',
    'giulia.painelli@escola.pr.gov.br': 'GIULIA DE LIMA PAINELLI',
    'kamily.santos.martins@escola.pr.gov.br': 'KAMILY DOS SANTOS MARTINS',
    'emanuelly.pierobom.peres@escola.pr.gov.br': 'EMANUELLY PIEROBOM PERES',
    'maria.nogueira.lopes@escola.pr.gov.br': 'MARIA JULIA DALAN NOGUEIRA LOPES',
    'sala.ana@escola.pr.gov.br': 'ANA BEATRIZ KLEIN',
    'rhenan.munhoz@escola.pr.gov.br': 'RHENAN SENE MUNHOZ',
    'josue.carlos.pereira@escola.pr.gov.br': 'JOSUÉ MATEUS CARLOS PEREIRA',
    'ariadnny.oliveira@escola.pr.gov.br': 'ARIADNNY KETTELLYN GAION DE OLIVEIRA',
    'ana.beatriz.klein@escola.pr.gov.br': 'ANA BEATRIZ KLEIN',
    'kemilly.aquino@escola.pr.gov.br': 'KEMILLY DE OLIVEIRA AQUINO',
    'leticia.munck@escola.pr.gov.br': 'LETÍCIA MUSETTI MUNCK',
    'januario.julia@escola.pr.gov.br': 'JÚLIA GALO JANUÁRIO',
    'eloa.cleto.souza@escola.pr.gov.br': 'ELOÁ ALARCON CLETO DE SOUZA',
    'murilo.ushida@escola.pr.gov.br': 'MURILO MASSASHI YAMASHITA USHIDA'
}

# emails_nomes = {
#     'juan.vieira.barros@escola.pr.gov.br': 'JUAN PABLO VIEIRA BARROS',
#     'leticia.santos.silva25@escola.pr.gov.br': 'LETICIA GABRIELLA SANTOS DA SILVA',
#     'lorainy.donaire@escola.pr.gov.br': 'LORAINY BEATRIZ DA SILVA DONAIRE',
#     'nicolly.agatha.nascimento@escola.pr.gov.br': 'NICOLLY AGATHA DO NASCIMENTO',
#     'neves.victoria@escola.pr.gov.br': 'VICTÓRIA EMANUELLY FERREIRA DAS NEVES',
#     'marijulene.goncalves@escola.pr.gov.br': 'MARIJULENE SILVA GONÇALVES',
#     'julio.fonseca.borges@escola.pr.gov.br': 'JULIO CESAR FONSECA BORGES',
#     'lima.silva.emanuelle@escola.pr.gov.br': 'EMANUELLE ROSA LIMA DA SILVA',
#     'regina.oliveira.layra@escola.pr.gov.br': 'LAYRA REGINA DE OLIVEIRA',
#     'paes.nathan@escola.pr.gov.br': 'NATHAN RODRIGUES PAES',
#     'livia.moco.moreira@escola.pr.gov.br': 'LIVIA TAVARES MOÇO MOREIRA',
#     'henrique.geraldo.araujo@escola.pr.gov.br': 'HENRIQUE GERALDO DE ARAUJO',
#     'joao.marques.adriano@escola.pr.gov.br': 'JOÃO LUCAS MARQUES ADRIANO',
#     'h.angelo@escola.pr.gov.br': 'HELOÍSA PEREIRA DO ANGELO',
#     'icaro.emanuel.silva@escola.pr.gov.br': 'ÍCARO EMANOEL DA SILVA',
#     'matheus.melo.guilherme@escola.pr.gov.br': 'MATHEUS BEZERRO DE MELO GUILHERME',
#     'nicoly.santos26@escola.pr.gov.br': 'NICOLY GABRIELLI OLIVEIRA DOS SANTOS',
#     'paola.larissa.bueno@escola.pr.gov.br': 'PAOLA LARISSA BUENO',
#     'sara.cantuario@escola.pr.gov.br': 'SARA SABRYNE ARAUJO CANTUARIO',
#     'ana.kremer@escola.pr.gov.br': 'ANA LUIZA BAPTISTA KREMER',
#     'karolaine.oliveira.borges@escola.pr.gov.br': 'KAROLAINE GONÇALVES DE OLIVEIRA BORGES',
#     'maria.melo.germano@escola.pr.gov.br': 'MARIA JULIA DE ANDRADE MELO GERMANO',
#     'bianca.rodrigues.oliveira31@escola.pr.gov.br': 'BIANCA RODRIGUES DE OLIVEIRA',
#     'maria.monteiro.oliveira05@escola.pr.gov.br': 'MARIA EDUARDA LIMA SILVA',
#     'maria.eduarda.lopes29@escola.pr.gov.br': 'MARIA EDUARDA LOPES',
#     'lima.silva.maria2307@escola.pr.gov.br': 'MARIA EDUARDA LIMA SILVA',
#     'pedro.pereira.souza18@escola.pr.gov.br': 'PEDRO HENRIQUE PEREIRA DE SOUZA',
#     'davi.silva.melo@escola.pr.gov.br': 'DAVI GABRIEL RODRIGUES DA SILVA MELO',
#     'lucas.puerta.guimaraes@escola.pr.gov.br': 'LUCAS PUERTA GUIMARÃES',
#     'lucas.gabriel.silva08@escola.pr.gov.br': 'LUCAS GABRIEL DA SILVA',
#     'felipe.luiz.freire@escola.pr.gov.br': 'FELIPE VIOL LUIZ FREIRE',
#     'giulia.painelli@escola.pr.gov.br': 'GIULIA DE LIMA PAINELLI',
#     'kamily.santos.martins@escola.pr.gov.br': 'KAMILY DOS SANTOS MARTINS',
#     'emanuelly.pierobom.peres@escola.pr.gov.br': 'EMANUELLY PIEROBOM PERES',
#     'maria.nogueira.lopes@escola.pr.gov.br': 'MARIA JULIA DALAN NOGUEIRA LOPES',
#     'sala.ana@escola.pr.gov.br': 'ANA BEATRIZ KLEIN',
#     'rhenan.munhoz@escola.pr.gov.br': 'RHENAN SENE MUNHOZ',
#     'josue.carlos.pereira@escola.pr.gov.br': 'JOSUÉ MATEUS CARLOS PEREIRA',
#     'ariadnny.oliveira@escola.pr.gov.br': 'ARIADNNY KETTELLYN GAION DE OLIVEIRA',
#     'ana.beatriz.klein@escola.pr.gov.br': 'ANA BEATRIZ KLEIN',
#     'kemilly.aquino@escola.pr.gov.br': 'KEMILLY DE OLIVEIRA AQUINO',
#     'leticia.munck@escola.pr.gov.br': 'LETÍCIA MUSETTI MUNCK',
#     'januario.julia@escola.pr.gov.br': 'JÚLIA GALO JANUÁRIO',
#     'eloa.cleto.souza@escola.pr.gov.br': 'ELOÁ ALARCON CLETO DE SOUZA',
#     'murilo.ushida@escola.pr.gov.br': 'MURILO MASSASHI YAMASHITA USHIDA'
# }
