[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="08b227090f2eb2045bc09e04561736dff12a3c8376d785770168c951df129c2a"

[auth.google]
client_id="72285654571-5edcdutr5khcn3kgm57bk8gunlmnq4ts.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"
